### ISSUE TITLE
カラーピッカーの実装

### ISSUE THREAD

**Issue by Shimosora** [IkanoOsushi/iKalendar#53]
明日、DBの処理の説明をお願いしたいです。
現状は、色の設定はできますがほかのコマの色を設定したときに前に設定したコマが同じ色になってしまいます。
プルリク出しときます。

**Comment by Shimosora** [comment]
今のところは、for文の背景色を設定する文をfor文の外に出すと今まで保存したすべての背景色が同じになるのを回避できたが、もともと選択していたボタンの背景色は白に戻ってしまうことを確認しました。
Intentで色を持ってくるのではなくTimetable_editActivityでDBにTimetable_color_idとして保存されている色をボタンの背景色として設定するやり方を考えましたがうまく動きませんでした。

**Comment by y-ogawara** [comment]
@Shimosora これってすでにプロジェクトに取り込まれてる？それともどこかのブランチ？コードだけ見て把握するのがしんどくなってきたのでビルドしたいっす！

**Comment by y-ogawara** [comment]
こちら、たぶんIntentで取得した色を入れてるので、データベースから取得した色を入れれば解決しそう。

**Comment by Shimosora** [comment]
実装できました！！！
ありがとうございます。
