### ISSUE TITLE
CalendarDayViewActivityからの予定編集からの上書きで落ちてしまう問題

### ISSUE THREAD

**Issue by kishimotoyk** [IkanoOsushi/iKalendar#64]
要するにイベントを上書きしようとするとエラー java.lang.ArrayIndexOutOfBoundsException: Out of range で落ちる
アプリ入れて予定をまず登録してから一回目上書きしようとすると確定で183行目で落ちるのに、その後もう一回同じイベントに対して上書きをしようとすると186行目で落ちたり187行目で落ちたりよくわからない

**Comment by ika3** [comment]
ちゃんと確認してないけどfor文のところでi<=hoge.size()と書いてるのでは？🤔
もしそうならi<hoge.size()にすればできるはずです

**Comment by kishimotoyk** [comment]
for文ないです

**Comment by kishimotoyk** [comment]
ちゃんとデータを入れられてるときは、Debuggerで確認した所画像一枚目のようにcalenders:sizeに1が入ってるみたいです
ただ、エラー吐いてるところはなぜかいきなり画像二枚目のようにcalenders:sizeが0になってしまいます
おそらくcalenders:sizeというものがいきなり0になってしまうのが原因
![2017-08-24 4 10 09](https://user-images.githubusercontent.com/19486845/29633745-35bcddfa-8882-11e7-9cc0-4dc6edbc197b.png)
![2017-08-24 4 10 29](https://user-images.githubusercontent.com/19486845/29633749-3e5b9988-8882-11e7-9452-585b1bef0025.png)

**Comment by kishimotoyk** [comment]
final RealmResults<Calender> calenders = calenderQuery.equalTo("calendar_title",beforeEditTitle).equalTo("calendar_start_hourofday",beforeEditStartHourOfDay).equalTo("calendar_start_minute",beforeEditStartMinute).equalTo("calendar_end_hourofday",beforeEditEndHourOfDay).equalTo("calendar_end_minute",beforeEditEndMinute).findAll();
とかいうかなり長い検索文のせいということはわかりました

**Comment by ika3** [comment]
私の手元にそのコードがないのでこれ以上の対応ができないです

**Comment by kishimotoyk** [comment]
もう寝るので明日伝えます

**Comment by kishimotoyk** [comment]
realmの検索機能ではなくifによって分けることによって解決しました
